spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true
logging:
    pattern:
        console: "%d %-5level %logger : %msg%n"
    level:
        org.springframework: WARN
        org.hibernate: WARN
